version: '3.3'

services:
  nodeexporter:
    image: prom/node-exporter:v1.1.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.rapl'
    restart: unless-stopped
    ports:
      - ${NODE_EXPORTER_PORT:-9100}:9100
    labels:
      org.label-schema.group: "monitoring"
      host.name: "${HOST_NAME}"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - '-housekeeping_interval=10s'
      - '-docker_only=true'
    restart: unless-stopped
    devices:
      - /dev/kmsg:/dev/kmsg
    security_opt:
      - no-new-privileges:true
    ports:
      - ${CADVISOR_PORT:-8080}:8080
    labels:
      org.label-schema.group: "monitoring"
      host.name: "${HOST_NAME}"

  nginxexporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginxexporter
    command:
      - '-nginx.scrape-uri=${NGINX_SCRAPE_URI:-http://localhost:8087/nginx_status}'
      - '-prometheus.const-labels=host=${HOST_NAME}'
    restart: unless-stopped
    ports:
      - ${NGINX_EXPORTER_PORT}:9113
    extra_hosts:
      - "host.docker.internal:${DOCKER_HOST_INTERNAL_IP}"
    labels:
      org.label-schema.group: "monitoring"
      host.name: "${HOST_NAME}"

  promtail:
    image: grafana/promtail:2.1.0
    container_name: promtail
    environment:
      - HOST_NAME
      - LOKI_EXTERNAL_URL
      - LOKI_USERNAME
      - LOKI_PASSWORD
    volumes:
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
      - promtail_data:/promtail/
      - /var/log:/var/log:ro
    command:
      - '-config.file=/etc/promtail/promtail.yml'
      - '-config.expand-env=true'
    labels:
      group: "monitoring"
      host.name: "${HOST_NAME}"

volumes:
  promtail_data: {}
